version: "3.3"
services:
  garbackend:
    container_name: garbackend
    image: docker.io/library/garbackend-v1
    restart: always
    networks:
      - default
    env_file:
      - apps/backend/.env
    environment:
      - DOMAIN=garapi.cerebrumtech.com.tr
      - VIRTUAL_HOST=garapi.cerebrumtech.com.tr
      - VIRTUAL_PORT=3000
    volumes:
      - ./log:/app/build/log
      - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  garfrontend:
    container_name: garfrontend
    image: docker.io/library/garfrontend-v1
    restart: always
    networks:
      - default
    environment:
      - DOMAIN=gar.cerebrumtech.com.tr
      - VIRTUAL_HOST=gar.cerebrumtech.com.tr
      - VIRTUAL_PORT=3000
    volumes:
      - ./log:/app/build/log
      - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
volumes:
  mongodb_data_container:
  redisDB:
  public:
networks:
  default:
    external:
      name: webproxy
