version: "3.3"
services:
  fuarbackend:
    container_name: fuarbackend
    image: docker.io/library/fuarbackend-v1
    restart: always
    networks:
      - default
    env_file:
      - apps/backend/.env
    environment:
      - DOMAIN=fuarapi.cerebrumtech.com.tr
      - VIRTUAL_HOST=fuarapi.cerebrumtech.com.tr
      - VIRTUAL_PORT=3000
    volumes:
      - ./log:/app/build/log
      - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  fuarfrontend:
    container_name: fuarfrontend
    image: docker.io/library/fuarfrontend-v1
    restart: always
    networks:
      - default
    environment:
      - DOMAIN=fuar.cerebrumtech.com.tr
      - VIRTUAL_HOST=fuar.cerebrumtech.com.tr
      - VIRTUAL_PORT=3000
    volumes:
      - ./log:/app/build/log
      - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
volumes:
  mongodb_data_container:
  redisDB:
  public:
networks:
  default:
    external:
      name: webproxy
