export const tr = {
  tr: {
    "Canlı Destek": "Canlı Destek",
    "Bir şeyler yazın...": "Bir şeyler yazın...",
    Gönder: "Gönder",
    "Klavyeyi Kapat": "Klavyeyi Kapat",
    "Geri Dön": "Geri Dön",
    Yenile: "Yenile",
    Çıkış: "Çıkış",
    Kapat: "Kapat",
    "Uçuş Bilgileri": "Uçuş Bilgileri",
    "QR Kod": "QR Kod",
    Harita: "Harita",
    "Uçuş Numarası": "Uçuş Numarası",
    Hedef: "Hedef",
    Durum: "Durum",
    "Son Güncelleme": "Son Güncelleme",
    İlerleme: "İlerleme",
  },
  en: {
    "Canlı Destek": "Live Support",
    "Bir şeyler yazın...": "Type something...",
    Gönder: "Send",
    "Klavyeyi Kapat": "Close Keyboard",
    "Geri Dön": "Back",
    Yenile: "Refresh",
    Çıkış: "Exit",
    Kapat: "Close",
    "Uçuş Bilgileri": "Flight Information",
    "QR Kod": "QR Code",
    Harita: "Map",
    "Uçuş Numarası": "Flight Number",
    Hedef: "Destination",
    Durum: "Status",
    "Son Güncelleme": "Last Update",
    İlerleme: "Progress",
  },
  de: {
    "Canlı Destek": "Live-Support",
    "Bir şeyler yazın...": "Schreiben Sie etwas...",
    Gönder: "Senden",
    "Klavyeyi Kapat": "Tastatur schließen",
    "Geri Dön": "Zurück",
    Yenile: "Aktualisieren",
    Çıkış: "Ausgang",
    Kapat: "Schließen",
    "Uçuş Bilgileri": "Fluginformationen",
    "QR Kod": "QR-Code",
    Harita: "Karte",
    "Uçuş Numarası": "Flugnummer",
    Hedef: "Ziel",
    Durum: "Status",
    "Son Güncelleme": "Letztes Update",
    İlerleme: "Fortschritt",
  },
  fr: {
    "Canlı Destek": "Support en direct",
    "Bir şeyler yazın...": "Tapez quelque chose...",
    Gönder: "Envoyer",
    "Klavyeyi Kapat": "Fermer le clavier",
    "Geri Dön": "Retour",
    Yenile: "Actualiser",
    Çıkış: "Sortie",
    Kapat: "Fermer",
    "Uçuş Bilgileri": "Informations sur le vol",
    "QR Kod": "Code QR",
    Harita: "Carte",
    "Uçuş Numarası": "Numéro de vol",
    Hedef: "Destination",
    Durum: "Statut",
    "Son Güncelleme": "Dernière mise à jour",
    İlerleme: "Progression",
  },
  it: {
    "Canlı Destek": "Supporto Live",
    "Bir şeyler yazın...": "Scrivi qualcosa...",
    Gönder: "Invia",
    "Klavyeyi Kapat": "Chiudi Tastiera",
    "Geri Dön": "Indietro",
    Yenile: "Ricarica",
    Çıkış: "Uscita",
    Kapat: "Chiudi",
    "Uçuş Bilgileri": "Informazioni sul volo",
    "QR Kod": "Codice QR",
    Harita: "Mappa",
    "Uçuş Numarası": "Numero di volo",
    Hedef: "Destinazione",
    Durum: "Stato",
    "Son Güncelleme": "Ultimo aggiornamento",
    İlerleme: "Progresso",
  },
  pt: {
    "Canlı Destek": "Suporte ao Vivo",
    "Bir şeyler yazın...": "Digite algo...",
    Gönder: "Enviar",
    "Klavyeyi Kapat": "Fechar Teclado",
    "Geri Dön": "Voltar",
    Yenile: "Atualizar",
    Çıkış: "Sair",
    Kapat: "Fechar",
    "Uçuş Bilgileri": "Informações do voo",
    "QR Kod": "Código QR",
    Harita: "Mapa",
    "Uçuş Numarası": "Número do voo",
    Hedef: "Destino",
    Durum: "Status",
    "Son Güncelleme": "Última atualização",
    İlerleme: "Progresso",
  },
  ar: {
    "Canlı Destek": "الدعم المباشر",
    "Bir şeyler yazın...": "اكتب شيئاً...",
    Gönder: "إرسال",
    "Klavyeyi Kapat": "إغلاق لوحة المفاتيح",
    "Geri Dön": "رجوع",
    Yenile: "تحديث",
    Çıkış: "خروج",
    Kapat: "إغلاق",
    "Uçuş Bilgileri": "معلومات الرحلة",
    "QR Kod": "رمز الاستجابة السريعة",
    Harita: "خريطة",
    "Uçuş Numarası": "رقم الرحلة",
    Hedef: "الوجهة",
    Durum: "الحالة",
    "Son Güncelleme": "آخر تحديث",
    İlerleme: "تقدم",
  },
  ru: {
    "Canlı Destek": "Поддержка онлайн",
    "Bir şeyler yazın...": "Введите что-нибудь...",
    Gönder: "Отправить",
    "Klavyeyi Kapat": "Закрыть клавиатуру",
    "Geri Dön": "Назад",
    Yenile: "Обновить",
    Çıkış: "Выход",
    Kapat: "Закрыть",
    "Uçuş Bilgileri": "Информация о рейсе",
    "QR Kod": "QR код",
    Harita: "Карта",
    "Uçuş Numarası": "Номер рейса",
    Hedef: "Место назначения",
    Durum: "Статус",
    "Son Güncelleme": "Последнее обновление",
    İlerleme: "Прогресс",
  },
  zh: {
    "Canlı Destek": "在线支持",
    "Bir şeyler yazın...": "输入一些内容...",
    Gönder: "发送",
    "Klavyeyi Kapat": "关闭键盘",
    "Geri Dön": "返回",
    Yenile: "刷新",
    Çıkış: "退出",
    Kapat: "关闭",
    "Uçuş Bilgileri": "航班信息",
    "QR Kod": "二维码",
    Harita: "地图",
    "Uçuş Numarası": "航班号",
    Hedef: "目的地",
    Durum: "状态",
    "Son Güncelleme": "最后更新",
    İlerleme: "进度",
  },
  es: {
    "Canlı Destek": "Soporte en vivo",
    "Bir şeyler yazın...": "Escribe algo...",
    Gönder: "Enviar",
    "Klavyeyi Kapat": "Cerrar teclado",
    "Geri Dön": "Volver",
    Yenile: "Actualizar",
    Çıkış: "Salir",
    Kapat: "Cerrar",
    "Uçuş Bilgileri": "Información del vuelo",
    "QR Kod": "Código QR",
    Harita: "Mapa",
    "Uçuş Numarası": "Número de vuelo",
    Hedef: "Destino",
    Durum: "Estado",
    "Son Güncelleme": "Última actualización",
    İlerleme: "Progreso",
  },
};
